import pytest
import pandas as pd

"""
Fixture example generated by

    np.random.seed(0)
    x = np.random.randint(20000, 40000, sample)
    km = np.random.choice(['Kvinna', 'Man'], sample)
    school = np.random.choice(['A', 'B', 'C'], sample)

"""

@pytest.fixture
def df():
    sample = 10
    _df = pd.DataFrame(
        dict(
            kr=[22732, 30799, 29845, 39648, 33123, 0,
               29225, 34116, 34935, 35430, 35832],
            km=['Kvinna', 'Kvinna', 'Kvinna', 'Man', 'Kvinna', 'Barn',
                'Man', 'Man', 'Kvinna', 'Kvinna', 'Man' ],
            school=['B', 'B', 'B', 'A', 'B', 'D',
                    'A', 'A', 'B', 'C', 'A'],
        )
    )
    return _df

@pytest.fixture
def active(df):
    return df[df.kr > 0]
